#!/bin/bash
HOME="/home/adilson"
DIR="$HOME/wallpapers"
if [[ -d "$DIR" ]]; then

	array=( "$DIR"/* )
	INTERVAL=`expr ${#array[*]} - 1`
	INTERVAL="0-$INTERVAL"

	RANDOMINDEX=$(shuf -i "$INTERVAL" -n 1)
	I=$RANDOMINDEX
	while true; do

		until [ $I -eq ${#array[*]} ]; do
			feh --bg-scale "${array["$I"]}"
			sleep 500
			let I+=1
		done
		I=0
	done
fi
